---
title: "Teaching"
description: |
  My lecture syllabus, and students' testimonials on Financial Modeling (FIN 4453) in Fall 2021. 
  Financial modeling course is the first course at UF that aims to teach modern technologies that is highly applicable for finance.
# author:
#   - name: Matthew Son 
#     # url: https://example.com/norajones
#     affiliation: University of Florida
    # affiliation_url: https://example.com/spacelysprokets
# date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


### Lecture Materials

1. [**Syllabus for FIN 4453**](files/FIN4453-Syllabus.pdf)

2. [**Course Schedule for Financial Modeling**](files/Course_Schedule.pdf)\

3. [**Installation Guide**](files/Install_guide.pdf)


### Course Description & Syllabus 


- This course is a hands-on, practice-based course with extensive use of spreadsheets and programming language. In particular, I'll teach you the workflow of financial modeling using Excel and Python (and some R). Practicing data manipulation, aggregation, visualization and statistical analyses in finance is the core part of the course.

- The objective of this course is to apply modeling techniques to solve financial problems. Topics include valuation of fixed income securities, portfolio management, and Monte Carlo simulation methods. Special topics such as data science in finance and machine learning will be introduced in the end if time permits.

- This course demands lots of time commitment. It will introduce a bunch of new technologies so those who are not technically inclined should expect to put in a lot of work. I will try to help everyone succeed in the course and build strong skills that would be applicable in a finance job, but your commitment is necessary. My goal is to make your programming experience enjoyable!




### Course Evaluation

- Instructor rating : 4.88 / 5.00  (Dept. Avg 3.81 / 5.00)

- [**Ph.D. Excellence in Teaching Award Winner**](https://news.warrington.ufl.edu/students/three-finance-and-accounting-phd-students-honored-with-teaching-awards/)


#### Students' Comments


- "Professor Son is highly enthusiastic and knowledgeable about the course. He presents information in a meaningful way and fosters an environment that is excellent for learning."

- "Engages the class very much and always is enthusiastic about the material. His knowledge of Python is very extensive and helped us understand it, given that most of us did not have prior coding experience."

- "Professor Son is extremely patient and knowledgeable. He always checks in with the class to ensure that all students are keeping up and understand the material. He asked for feedback many times and altered the class schedule to fit our class needs. He is highly adaptable."

-  "Professor Son was always very accommodating and willing to provide extra help and give extended explanations when needed. He was also very responsive outside of class and was observant to how the class reacts to the difficult of the material and would adjust if needed."

-  "Professor Son did a great job covering a wide range of python and excel uses for financial modeling. He was flexible in the pace of the class to ensure all the students were on the same page. He made the class interactive as I could follow along on my own python file. The lab problems at the end of class also helped give us more practice."

- "Very smart person with excellent teaching abilities"

- "Professor Sons enthusiasm and excitement of teaching this course is what made this course interactive. He provided regular feedback on all of my assignments which were really helpful to me."

- "His strengths were in having his own deep understanding of the concepts that were being taught as well as being flexible and personal with his students."

- "I loved everything about this course."

- "This has probably been my favorite finance course."

- "I think the most valuable thing I've learned is being able to understand how python works and being able to use it for a finance purpose. I believe if I tried to learn python on my own, it would take a lot longer to master the concepts, but this class has helped tremendously, especially with Professor Son helping out with every step."


